name = "condescending-jang"
org = "f71d6370-612b-4f6c-a9fb-2bea0133c2e9"
git-url = "https://github.com/Shilpahks26/react_password_generator"
git-branch = "main"
git-provider = "github"
framework = "React"
install = "npm install"
build = "npm run build"
output = "build"
